### ISSUE TITLE
Manual Authenticate

### ISSUE THREAD

**Issue by triastanto** [Fuitad/laravel-exchange-web-services#1]
How do I manually authenticate exchange user without config file (.ENV)?

**Comment by Fuitad** [comment]
Check the test case EwsFactoryTest.php (https://github.com/Fuitad/laravel-exchange-web-services/blob/master/tests/EwsFactoryTest.php). It should give you a good idea how to do it :)

**Comment by triastanto** [comment]
Thank you so much for your clear response.
Btw I am totally new to laravel, getting a grasp to the new concept of Depedency Injection, Service Provider, Service Container, Facades, Contract, binding, singleton makes me a little bit confuse (actually a lot :dancers:. I don't know how to apply those code into my project, moreover I need the user logs into system via ADLDAP (laravel package also) and authenticate this package too, ultimately, my project needs to retrieve the number of inbox, events, and its details.

**Comment by Fuitad** [comment]
No problem. If you're just getting started with Laravel, you might want to consider getting a membership at www.laracasts.com. I highly recommend it.
