### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by triastanto** [Fuitad/laravel-exchange-web-services#2]
Why am I getting this message? Previously I did connect properly and was able to retrieve the messages.

`ErrorException in ExchangeClient.php line 240:`
`Trying to get property of non-object`

`in ExchangeClient.php line 240`
`at HandleExceptions->handleError('8', 'Trying to get property of non-object', 'D:\triastanto\Dropbox\htdocs\ColorSSO\vendor\fuitad\exchange-web-services-for-php\src\ExchangeClient.php', '240', array('limit' => '5', 'onlyunread' => true, 'folder' => 'inbox', 'folderIdIsDistinguishedFolderId' => true, 'FindItem' => object(stdClass), 'response' => null)) in ExchangeClient.php line 240`
`at ExchangeClient->get_messages('5', true)`
`at call_user_func_array(array(object(ExchangeClient), 'get_messages'), array('5', true)) in AbstractManager.php line 234`
`at AbstractManager->__call('get_messages', array('5', true)) in Facade.php line 219`
`at EwsManager->get_messages('5', true) in Facade.php line 219`
`at Facade::__callStatic('get_messages', array('5', true)) in PagesController.php line 94`
`at ExchangeWebServices::get_messages('5', true) in PagesController.php line 94`

FYI, I didn't use the full url to the wsdl file instead  I followed your instruction on packagist about advanced installation because of `Start tag expected, '<' not found` error by retrieving 3 files
`http://exchange.server.local/EWS/Services.wsdl`
`http://exchange.server.local/EWS/messages.xsd`
`http://exchange.server.local/EWS/types.xsd`
,modify the tail of the content & copying those files into vendor\fuitad\exchange-web-services-for-php\src folder.

Thanks in advance.

**Comment by Fuitad** [comment]
Without seeing your code, it's a bit hard to say. Is it possible that you're trying to read from a folder that doesn't exist?
