### ISSUE TITLE
Support for Laravel 5.4

### ISSUE THREAD

**Issue by MyIgel** [Fuitad/laravel-exchange-web-services#3]
Is Laravel 5.4 support planned?

**Comment by Fuitad** [comment]
Sorry, I totally missed this issue. I'm gonna look into it and see if I can make it happen.

**Comment by bodybag** [comment]
^ Would love to see this happen.

**Comment by Fuitad** [comment]
Still need to make this happen. Probably for Laravel 5.5.

**Comment by mitomitov** [comment]
Hi, will there be support for Laravel 5.5 and when? Thanks.

**Comment by Kershrew** [comment]
You can do it man, I believe in you!

**Comment by shaileshjlloyds** [comment]
how to send mail through laravel exchange web services

**Comment by shaileshjlloyds** [comment]
can we use it with laravel 5.4.
Its throwing errors on composer update
Installation request for fuitad/laravel-exchange-web-services ^1.0 -> satisfiable by fuitad/laravel-exchange-web-services[1.0.0].
    - Conclusion: remove laravel/framework v5.4.36
    - Conclusion: don't install laravel/framework v5.4.36

**Comment by Fuitad** [comment]
@shaileshjlloyds unfortunately, this package is no longer supported and does not support Laravel 5.4 sorry.

**Comment by MyIgel** [comment]
So it should be archived and explicitly flagged as deprecated?
