### ISSUE TITLE
Send message

### ISSUE THREAD

**Issue by MSherali** [Fuitad/laravel-exchange-web-services#4]
Hello is it possible to send a message.  
I'm doing this. 
// code
ExchangeWebServices::send_message("sheralim@gmail.com","Test Soap","Test email"); 

//error
Creating default object from empty value

**Comment by Fuitad** [comment]
Hi there,

This package is only compatible with EWS (Exchange Web Services). Gmail is not hosted on Exchange (which is a Microsoft platform). 

In a nutshell, it won't work.

**Comment by MSherali** [comment]
Is it possible to send an email to "sheralim@gmail.com" using this package. I'm using local Exchange server and my account credentials to connect. i could read message, but couln't send message.
